

services:
  backend:
    build: ./backend
    container_name: dataanalysis-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./dashboard-frontend
    container_name: dataanalysis-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
